// ─────────────────────────────────────────────────────────────────────────────
// PARTEQUIPOS SAS — Comprehensive Mock Data
// ─────────────────────────────────────────────────────────────────────────────

// ── Types ─────────────────────────────────────────────────────────────────────

export type MachineStatus = "operational" | "maintenance" | "idle" | "critical";
export type MaintenanceStatus = "scheduled" | "in_progress" | "completed" | "overdue";
export type PartCategory = "filtros" | "correas" | "lubricantes" | "hidraulicos" | "electrico" | "neumaticos" | "frenos" | "motor";
export type UserRole = "Administrator" | "Coordinator" | "Sales Advisor" | "Technician" | "Viewer";
export type AuditAction = "CREATE" | "UPDATE" | "DELETE" | "VIEW" | "EXPORT" | "LOGIN" | "LOGOUT";

export interface Machine {
  id: string;
  serialNumber: string;
  model: string;
  brand: string;
  year: number;
  status: MachineStatus;
  customerId: string;
  customerName: string;
  location: string;
  city: string;
  coordinates: { lat: number; lng: number };
  hoursOperated: number;
  lastMaintenanceDate: string;
  nextMaintenanceDate: string;
  nextMaintenanceHours: number;
  imageUrl: string;
  category: string;
  engineModel: string;
  weight: number; // kg
  notes: string;
}

export interface MaintenancePart {
  partId: string;
  sapCode: string;
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface MaintenanceActivity {
  id: string;
  code: string;
  name: string;
  description: string;
  category: string;
  laborHours: number;
  laborRate: number; // COP per hour
  parts: MaintenancePart[];
  consumables: MaintenancePart[];
  totalPartsPrice: number;
  totalConsumablesPrice: number;
  totalLaborPrice: number;
  totalPrice: number;
  intervalHours: number;
  intervalMonths: number;
  applicableBrands: string[];
  estimatedDuration: string;
  techniciansRequired: number;
}

export interface SparePart {
  id: string;
  sapCode: string;
  partNumber: string;
  description: string;
  brand: string;
  category: PartCategory;
  compatibleMachines: string[];
  stock: number;
  minStock: number;
  warehouse: string;
  location: string; // shelf/bin
  unitPrice: number; // COP
  listPrice: number;
  discountPct: number;
  weight: number; // kg
  leadTimeDays: number;
  imageUrl: string;
  isActive: boolean;
  lastUpdated: string;
}

export interface Customer {
  id: string;
  name: string;
  nit: string;
  contact: string;
  email: string;
  phone: string;
  city: string;
  address: string;
  segment: string;
  assignedAdvisor: string;
  machinesCount: number;
  totalRevenue: number;
  createdAt: string;
}

export interface MaintenanceSchedule {
  id: string;
  machineId: string;
  machineName: string;
  customerId: string;
  customerName: string;
  activityId: string;
  activityName: string;
  status: MaintenanceStatus;
  scheduledDate: string;
  completedDate?: string;
  technicianId: string;
  technicianName: string;
  estimatedHours: number;
  actualHours?: number;
  totalCost: number;
  notes: string;
  workOrderNumber: string;
}

export interface DashboardKPI {
  totalMachines: number;
  operationalMachines: number;
  machinesInMaintenance: number;
  idleMachines: number;
  criticalMachines: number;
  scheduledMaintenances: number;
  completedMaintenancesThisMonth: number;
  overdueMaintenances: number;
  totalPartsInStock: number;
  lowStockParts: number;
  monthlyRevenue: number;
  revenueGrowth: number; // percentage
  totalCustomers: number;
  activeCustomers: number;
  avgMaintenanceCost: number;
  partsOrderedThisMonth: number;
  monthlyRevenueHistory: { month: string; revenue: number; target: number }[];
  maintenanceByBrand: { brand: string; count: number; color: string }[];
  machineStatusDistribution: { status: string; count: number; color: string }[];
  topPartsConsumed: { name: string; quantity: number; revenue: number }[];
}

export interface ActivityLog {
  id: string;
  timestamp: string;
  userId: string;
  userName: string;
  userRole: UserRole;
  action: string;
  module: string;
  description: string;
  entityId?: string;
  entityType?: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar: string;
  department: string;
  phone: string;
  isActive: boolean;
  lastLogin: string;
  createdAt: string;
  permissions: string[];
}

export interface AuditLog {
  id: string;
  timestamp: string;
  userId: string;
  userName: string;
  action: AuditAction;
  module: string;
  entityId: string;
  entityType: string;
  changes?: { field: string; oldValue: string; newValue: string }[];
  ipAddress: string;
  userAgent: string;
}

export interface ColombiaCity {
  name: string;
  department: string;
  lat: number;
  lng: number;
  machineCount: number;
}

// ── Colombia Cities ────────────────────────────────────────────────────────────

export const COLOMBIA_CITIES: ColombiaCity[] = [
  { name: "Bogotá", department: "Cundinamarca", lat: 4.711, lng: -74.0721, machineCount: 4 },
  { name: "Medellín", department: "Antioquia", lat: 6.2442, lng: -75.5812, machineCount: 3 },
  { name: "Cali", department: "Valle del Cauca", lat: 3.4516, lng: -76.532, machineCount: 2 },
  { name: "Barranquilla", department: "Atlántico", lat: 10.9685, lng: -74.7813, machineCount: 2 },
  { name: "Bucaramanga", department: "Santander", lat: 7.1193, lng: -73.1227, machineCount: 2 },
  { name: "Cartagena", department: "Bolívar", lat: 10.391, lng: -75.4794, machineCount: 1 },
  { name: "Cúcuta", department: "Norte de Santander", lat: 7.8939, lng: -72.5078, machineCount: 1 },
];

// ── Customers ─────────────────────────────────────────────────────────────────

export const CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Constructora Bolívar S.A.",
    nit: "860.007.336-1",
    contact: "Carlos Mendoza",
    email: "cmendoza@constructorabolivar.com",
    phone: "+57 1 310 5000",
    city: "Bogotá",
    address: "Cra 7 # 77-07, Bogotá",
    segment: "Construcción",
    assignedAdvisor: "user-004",
    machinesCount: 4,
    totalRevenue: 285000000,
    createdAt: "2021-03-15",
  },
  {
    id: "cust-002",
    name: "Mineros S.A.",
    nit: "890.400.567-3",
    contact: "Lucía Restrepo",
    email: "lrestrepo@mineros.com.co",
    phone: "+57 4 444 3000",
    city: "Medellín",
    address: "Cl 10 Sur # 50-20, Medellín",
    segment: "Minería",
    assignedAdvisor: "user-004",
    machinesCount: 3,
    totalRevenue: 520000000,
    createdAt: "2020-06-01",
  },
  {
    id: "cust-003",
    name: "Cementos Argos S.A.",
    nit: "890.100.251-6",
    contact: "Andrés Villegas",
    email: "avillegas@argos.com.co",
    phone: "+57 4 604 0100",
    city: "Medellín",
    address: "Cl 7 # 43B-100, Medellín",
    segment: "Manufactura",
    assignedAdvisor: "user-004",
    machinesCount: 2,
    totalRevenue: 198000000,
    createdAt: "2019-11-20",
  },
  {
    id: "cust-004",
    name: "Grupo Odinsa S.A.S.",
    nit: "800.111.469-7",
    contact: "Patricia Suárez",
    email: "psuarez@odinsa.com",
    phone: "+57 1 346 9400",
    city: "Bogotá",
    address: "Av El Dorado # 92-32, Bogotá",
    segment: "Infraestructura",
    assignedAdvisor: "user-004",
    machinesCount: 2,
    totalRevenue: 310000000,
    createdAt: "2020-02-14",
  },
  {
    id: "cust-005",
    name: "Caribbean Port Services",
    nit: "900.123.456-8",
    contact: "Roberto Paez",
    email: "rpaez@caribport.com",
    phone: "+57 5 660 1234",
    city: "Cartagena",
    address: "Zona Franca La Candelaria, Cartagena",
    segment: "Puertos y Logística",
    assignedAdvisor: "user-004",
    machinesCount: 1,
    totalRevenue: 145000000,
    createdAt: "2022-01-10",
  },
  {
    id: "cust-006",
    name: "Empresas Públicas de Medellín",
    nit: "890.904.996-1",
    contact: "Diana Torres",
    email: "dtorres@epm.com.co",
    phone: "+57 4 444 4696",
    city: "Medellín",
    address: "Cl 30 # 43-113, Medellín",
    segment: "Servicios Públicos",
    assignedAdvisor: "user-004",
    machinesCount: 1,
    totalRevenue: 89000000,
    createdAt: "2021-08-05",
  },
  {
    id: "cust-007",
    name: "Vías de Colombia S.A.S.",
    nit: "900.456.789-2",
    contact: "Jorge Martínez",
    email: "jmartinez@viasdecolombia.com",
    phone: "+57 7 634 5000",
    city: "Bucaramanga",
    address: "Cra 15 # 93-75, Bucaramanga",
    segment: "Infraestructura",
    assignedAdvisor: "user-004",
    machinesCount: 1,
    totalRevenue: 220000000,
    createdAt: "2020-09-18",
  },
  {
    id: "cust-008",
    name: "Palmas del Llano S.A.",
    nit: "800.234.567-4",
    contact: "Alejandro Rivas",
    email: "arivas@palmasllano.com",
    phone: "+57 8 682 3000",
    city: "Barranquilla",
    address: "Vía 40 # 35-81, Barranquilla",
    segment: "Agroindustria",
    assignedAdvisor: "user-004",
    machinesCount: 1,
    totalRevenue: 112000000,
    createdAt: "2022-05-22",
  },
];

// ── Machines ──────────────────────────────────────────────────────────────────

export const MACHINES: Machine[] = [
  {
    id: "maq-001",
    serialNumber: "CAT-D6T-2021-COL001",
    model: "D6T",
    brand: "Caterpillar",
    year: 2021,
    status: "operational",
    customerId: "cust-001",
    customerName: "Constructora Bolívar S.A.",
    location: "Obra Norte, Bogotá",
    city: "Bogotá",
    coordinates: { lat: 4.7482, lng: -74.0394 },
    hoursOperated: 3420,
    lastMaintenanceDate: "2024-10-15",
    nextMaintenanceDate: "2025-01-15",
    nextMaintenanceHours: 3500,
    imageUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400",
    category: "Bulldozer",
    engineModel: "Cat C9.3B ACERT",
    weight: 22156,
    notes: "Operando en turno nocturno. Revisar sistema de refrigeración próximo mantenimiento.",
  },
  {
    id: "maq-002",
    serialNumber: "KOM-PC360-2020-COL002",
    model: "PC360-10",
    brand: "Komatsu",
    year: 2020,
    status: "maintenance",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    location: "Mina El Torito, Antioquia",
    city: "Medellín",
    coordinates: { lat: 6.3246, lng: -75.4893 },
    hoursOperated: 8750,
    lastMaintenanceDate: "2024-11-01",
    nextMaintenanceDate: "2025-02-01",
    nextMaintenanceHours: 9000,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
    category: "Excavadora",
    engineModel: "SAA6D114E-5",
    weight: 36900,
    notes: "En mantenimiento preventivo programado. Cambio de sellos hidráulicos.",
  },
  {
    id: "maq-003",
    serialNumber: "VOL-EC480-2022-COL003",
    model: "EC480E",
    brand: "Volvo",
    year: 2022,
    status: "operational",
    customerId: "cust-003",
    customerName: "Cementos Argos S.A.",
    location: "Planta Rioclaro, Antioquia",
    city: "Medellín",
    coordinates: { lat: 5.9167, lng: -74.8667 },
    hoursOperated: 2180,
    lastMaintenanceDate: "2024-11-20",
    nextMaintenanceDate: "2025-02-20",
    nextMaintenanceHours: 2500,
    imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400",
    category: "Excavadora",
    engineModel: "Volvo D13J",
    weight: 47200,
    notes: "Excelente condición. Operador certificado asignado.",
  },
  {
    id: "maq-004",
    serialNumber: "JD-770G-2021-COL004",
    model: "770G",
    brand: "John Deere",
    year: 2021,
    status: "operational",
    customerId: "cust-004",
    customerName: "Grupo Odinsa S.A.S.",
    location: "Proyecto Vial Cundinamarca",
    city: "Bogotá",
    coordinates: { lat: 4.6097, lng: -74.0817 },
    hoursOperated: 4560,
    lastMaintenanceDate: "2024-10-30",
    nextMaintenanceDate: "2025-01-30",
    nextMaintenanceHours: 5000,
    imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400",
    category: "Motoniveladora",
    engineModel: "John Deere PowerTech 6068H",
    weight: 17690,
    notes: "Operando en conformación de calzada, Variante Siberia.",
  },
  {
    id: "maq-005",
    serialNumber: "BOB-S770-2023-COL005",
    model: "S770",
    brand: "Bobcat",
    year: 2023,
    status: "idle",
    customerId: "cust-001",
    customerName: "Constructora Bolívar S.A.",
    location: "Bodega Central Bogotá",
    city: "Bogotá",
    coordinates: { lat: 4.6782, lng: -74.1273 },
    hoursOperated: 540,
    lastMaintenanceDate: "2024-09-10",
    nextMaintenanceDate: "2025-03-10",
    nextMaintenanceHours: 1000,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    category: "Minicargador",
    engineModel: "Bobcat 3.4L Diesel",
    weight: 3860,
    notes: "En bodega, disponible para nueva asignación.",
  },
  {
    id: "maq-006",
    serialNumber: "HIT-ZX350-2020-COL006",
    model: "ZX350LC-6",
    brand: "Hitachi",
    year: 2020,
    status: "critical",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    location: "Mina La Frontera, Antioquia",
    city: "Medellín",
    coordinates: { lat: 6.4215, lng: -75.6332 },
    hoursOperated: 12340,
    lastMaintenanceDate: "2024-08-15",
    nextMaintenanceDate: "2024-11-15",
    nextMaintenanceHours: 12500,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
    category: "Excavadora",
    engineModel: "Isuzu 6HK1X",
    weight: 34600,
    notes: "⚠️ ALERTA: Fuga hidráulica detectada. Requiere intervención urgente.",
  },
  {
    id: "maq-007",
    serialNumber: "LIE-LTM1100-2019-COL007",
    model: "LTM 1100-5.2",
    brand: "Liebherr",
    year: 2019,
    status: "operational",
    customerId: "cust-005",
    customerName: "Caribbean Port Services",
    location: "Puerto de Cartagena, Muelle 5",
    city: "Cartagena",
    coordinates: { lat: 10.3978, lng: -75.4965 },
    hoursOperated: 6700,
    lastMaintenanceDate: "2024-11-05",
    nextMaintenanceDate: "2025-02-05",
    nextMaintenanceHours: 7000,
    imageUrl: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400",
    category: "Grúa Telescópica",
    engineModel: "Liebherr D9508 A7",
    weight: 60000,
    notes: "Operación portuaria continua. Cumple con certificación ICONTEC.",
  },
  {
    id: "maq-008",
    serialNumber: "CAS-580SN-2022-COL008",
    model: "580SN WT",
    brand: "Case",
    year: 2022,
    status: "operational",
    customerId: "cust-006",
    customerName: "Empresas Públicas de Medellín",
    location: "Proyecto Acueducto Medellín Norte",
    city: "Medellín",
    coordinates: { lat: 6.2971, lng: -75.5624 },
    hoursOperated: 1870,
    lastMaintenanceDate: "2024-11-25",
    nextMaintenanceDate: "2025-02-25",
    nextMaintenanceHours: 2000,
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    category: "Retroexcavadora",
    engineModel: "FPT F4HFE613*A002",
    weight: 8200,
    notes: "Excavación de zanjas para red de acueducto.",
  },
  {
    id: "maq-009",
    serialNumber: "JCB-3CX-2023-COL009",
    model: "3CX Pro",
    brand: "JCB",
    year: 2023,
    status: "operational",
    customerId: "cust-007",
    customerName: "Vías de Colombia S.A.S.",
    location: "Proyecto Vial Santander",
    city: "Bucaramanga",
    coordinates: { lat: 7.1254, lng: -73.1198 },
    hoursOperated: 980,
    lastMaintenanceDate: "2024-12-01",
    nextMaintenanceDate: "2025-03-01",
    nextMaintenanceHours: 1000,
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    category: "Retroexcavadora",
    engineModel: "JCB EcoMAX 4CX 55kW",
    weight: 8100,
    notes: "Máquina nueva. Primera revisión próxima a las 1000 horas.",
  },
  {
    id: "maq-010",
    serialNumber: "DOS-DX380-2020-COL010",
    model: "DX380LC-7",
    brand: "Doosan",
    year: 2020,
    status: "maintenance",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    location: "Mina El Torito, Antioquia",
    city: "Medellín",
    coordinates: { lat: 6.3456, lng: -75.5012 },
    hoursOperated: 9200,
    lastMaintenanceDate: "2024-11-10",
    nextMaintenanceDate: "2025-02-10",
    nextMaintenanceHours: 9500,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
    category: "Excavadora",
    engineModel: "Doosan DL06P",
    weight: 38700,
    notes: "Mantenimiento mayor: cambio de bomba hidráulica.",
  },
  {
    id: "maq-011",
    serialNumber: "CAT-336-2022-COL011",
    model: "336",
    brand: "Caterpillar",
    year: 2022,
    status: "operational",
    customerId: "cust-004",
    customerName: "Grupo Odinsa S.A.S.",
    location: "Proyecto Autopista Bogotá-Girardot",
    city: "Bogotá",
    coordinates: { lat: 4.4893, lng: -74.3521 },
    hoursOperated: 3100,
    lastMaintenanceDate: "2024-10-20",
    nextMaintenanceDate: "2025-01-20",
    nextMaintenanceHours: 3500,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
    category: "Excavadora",
    engineModel: "Cat C9.3B ACERT",
    weight: 35900,
    notes: "Excavación de fundaciones para viaducto.",
  },
  {
    id: "maq-012",
    serialNumber: "KOM-WA480-2021-COL012",
    model: "WA480-8",
    brand: "Komatsu",
    year: 2021,
    status: "idle",
    customerId: "cust-003",
    customerName: "Cementos Argos S.A.",
    location: "Planta Yumbo, Valle del Cauca",
    city: "Cali",
    coordinates: { lat: 3.5896, lng: -76.4972 },
    hoursOperated: 5430,
    lastMaintenanceDate: "2024-09-25",
    nextMaintenanceDate: "2025-03-25",
    nextMaintenanceHours: 6000,
    imageUrl: "https://images.unsplash.com/photo-1534189485647-de4fdad0bd3c?w=400",
    category: "Cargador Frontal",
    engineModel: "SAA6D125E-7",
    weight: 27600,
    notes: "Parado por baja demanda en planta. Listo para reasignación.",
  },
  {
    id: "maq-013",
    serialNumber: "VOL-A40G-2019-COL013",
    model: "A40G",
    brand: "Volvo",
    year: 2019,
    status: "critical",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    location: "Mina La Frontera, Antioquia",
    city: "Medellín",
    coordinates: { lat: 6.4102, lng: -75.6215 },
    hoursOperated: 15600,
    lastMaintenanceDate: "2024-07-30",
    nextMaintenanceDate: "2024-10-30",
    nextMaintenanceHours: 16000,
    imageUrl: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400",
    category: "Camión Articulado",
    engineModel: "Volvo D13H",
    weight: 28500,
    notes: "⚠️ CRÍTICO: Sobrepasó intervalo de mantenimiento. Suspender operación.",
  },
  {
    id: "maq-014",
    serialNumber: "JD-872GP-2022-COL014",
    model: "872 GP",
    brand: "John Deere",
    year: 2022,
    status: "operational",
    customerId: "cust-008",
    customerName: "Palmas del Llano S.A.",
    location: "Finca El Palmar, Meta",
    city: "Barranquilla",
    coordinates: { lat: 10.9845, lng: -74.7931 },
    hoursOperated: 2760,
    lastMaintenanceDate: "2024-11-15",
    nextMaintenanceDate: "2025-02-15",
    nextMaintenanceHours: 3000,
    imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400",
    category: "Motoniveladora",
    engineModel: "John Deere PowerTech 6090H",
    weight: 19780,
    notes: "Mantenimiento de vías internas de la finca.",
  },
  {
    id: "maq-015",
    serialNumber: "CAT-950M-2023-COL015",
    model: "950M",
    brand: "Caterpillar",
    year: 2023,
    status: "operational",
    customerId: "cust-001",
    customerName: "Constructora Bolívar S.A.",
    location: "Obra Occidente, Bogotá",
    city: "Bogotá",
    coordinates: { lat: 4.6901, lng: -74.1547 },
    hoursOperated: 1240,
    lastMaintenanceDate: "2024-12-01",
    nextMaintenanceDate: "2025-03-01",
    nextMaintenanceHours: 2000,
    imageUrl: "https://images.unsplash.com/photo-1534189485647-de4fdad0bd3c?w=400",
    category: "Cargador Frontal",
    engineModel: "Cat C7.1 ACERT",
    weight: 18000,
    notes: "Máquina reciente. Operando en proyecto urbanístico.",
  },
];

// ── Spare Parts ───────────────────────────────────────────────────────────────

export const SPARE_PARTS: SparePart[] = [
  {
    id: "part-001",
    sapCode: "CPP-1001-SA",
    partNumber: "1R-0750",
    description: "Filtro de Aceite Motor Caterpillar - Serie C9/C9.3",
    brand: "Caterpillar",
    category: "filtros",
    compatibleMachines: ["maq-001", "maq-011", "maq-015"],
    stock: 24,
    minStock: 10,
    warehouse: "Bodega Bogotá",
    location: "A-01-03",
    unitPrice: 185000,
    listPrice: 210000,
    discountPct: 12,
    weight: 0.85,
    leadTimeDays: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-01",
  },
  {
    id: "part-002",
    sapCode: "CPP-1002-SA",
    partNumber: "600-311-3110",
    description: "Filtro Combustible Komatsu PC360/WA480",
    brand: "Komatsu",
    category: "filtros",
    compatibleMachines: ["maq-002", "maq-010", "maq-012"],
    stock: 18,
    minStock: 8,
    warehouse: "Bodega Medellín",
    location: "B-02-01",
    unitPrice: 145000,
    listPrice: 168000,
    discountPct: 14,
    weight: 0.62,
    leadTimeDays: 5,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-28",
  },
  {
    id: "part-003",
    sapCode: "CPP-1003-SA",
    partNumber: "21707132",
    description: "Filtro Hidráulico Volvo EC480/A40G",
    brand: "Volvo",
    category: "hidraulicos",
    compatibleMachines: ["maq-003", "maq-013"],
    stock: 12,
    minStock: 6,
    warehouse: "Bodega Medellín",
    location: "C-03-02",
    unitPrice: 320000,
    listPrice: 380000,
    discountPct: 16,
    weight: 1.2,
    leadTimeDays: 7,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-30",
  },
  {
    id: "part-004",
    sapCode: "CPP-1004-SA",
    partNumber: "AT171853",
    description: "Correa Serpentina John Deere PowerTech 6068H",
    brand: "John Deere",
    category: "correas",
    compatibleMachines: ["maq-004", "maq-014"],
    stock: 8,
    minStock: 4,
    warehouse: "Bodega Bogotá",
    location: "D-01-05",
    unitPrice: 89000,
    listPrice: 102000,
    discountPct: 13,
    weight: 0.45,
    leadTimeDays: 4,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-02",
  },
  {
    id: "part-005",
    sapCode: "CPP-1005-SA",
    partNumber: "6693256",
    description: "Filtro de Aire Primario Bobcat S770",
    brand: "Bobcat",
    category: "filtros",
    compatibleMachines: ["maq-005"],
    stock: 15,
    minStock: 6,
    warehouse: "Bodega Bogotá",
    location: "A-02-04",
    unitPrice: 125000,
    listPrice: 145000,
    discountPct: 14,
    weight: 0.78,
    leadTimeDays: 5,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-25",
  },
  {
    id: "part-006",
    sapCode: "CPP-1006-SA",
    partNumber: "4421776",
    description: "Sello Hidráulico Hitachi ZX350 - Kit Brazo",
    brand: "Hitachi",
    category: "hidraulicos",
    compatibleMachines: ["maq-006"],
    stock: 3,
    minStock: 5,
    warehouse: "Bodega Medellín",
    location: "C-04-01",
    unitPrice: 680000,
    listPrice: 790000,
    discountPct: 14,
    weight: 0.9,
    leadTimeDays: 14,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-20",
  },
  {
    id: "part-007",
    sapCode: "CPP-1007-SA",
    partNumber: "10002780",
    description: "Aceite Motor SAE 15W-40 - Liebherr (Bid. 20L)",
    brand: "Liebherr",
    category: "lubricantes",
    compatibleMachines: ["maq-007"],
    stock: 30,
    minStock: 15,
    warehouse: "Bodega Cartagena",
    location: "E-01-02",
    unitPrice: 420000,
    listPrice: 490000,
    discountPct: 14,
    weight: 18.5,
    leadTimeDays: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-01",
  },
  {
    id: "part-008",
    sapCode: "CPP-1008-SA",
    partNumber: "87802042",
    description: "Filtro Hidráulico Case 580SN",
    brand: "Case",
    category: "filtros",
    compatibleMachines: ["maq-008"],
    stock: 20,
    minStock: 8,
    warehouse: "Bodega Medellín",
    location: "B-03-03",
    unitPrice: 175000,
    listPrice: 204000,
    discountPct: 14,
    weight: 0.75,
    leadTimeDays: 5,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-29",
  },
  {
    id: "part-009",
    sapCode: "CPP-1009-SA",
    partNumber: "320/07237",
    description: "Bomba Hidráulica JCB 3CX - Principal",
    brand: "JCB",
    category: "hidraulicos",
    compatibleMachines: ["maq-009"],
    stock: 2,
    minStock: 3,
    warehouse: "Bodega Bogotá",
    location: "F-01-01",
    unitPrice: 4850000,
    listPrice: 5600000,
    discountPct: 13,
    weight: 12.5,
    leadTimeDays: 21,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-15",
  },
  {
    id: "part-010",
    sapCode: "CPP-1010-SA",
    partNumber: "2455702",
    description: "Bomba Hidráulica Doosan DX380 - Tandem",
    brand: "Doosan",
    category: "hidraulicos",
    compatibleMachines: ["maq-010"],
    stock: 1,
    minStock: 2,
    warehouse: "Bodega Medellín",
    location: "C-05-01",
    unitPrice: 7200000,
    listPrice: 8400000,
    discountPct: 14,
    weight: 18.2,
    leadTimeDays: 30,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-10",
  },
  {
    id: "part-011",
    sapCode: "CPP-1011-SA",
    partNumber: "1R-0739",
    description: "Filtro de Aceite Hidráulico Caterpillar 336/950M",
    brand: "Caterpillar",
    category: "filtros",
    compatibleMachines: ["maq-011", "maq-015"],
    stock: 22,
    minStock: 10,
    warehouse: "Bodega Bogotá",
    location: "A-01-04",
    unitPrice: 215000,
    listPrice: 250000,
    discountPct: 14,
    weight: 0.95,
    leadTimeDays: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-02",
  },
  {
    id: "part-012",
    sapCode: "CPP-1012-SA",
    partNumber: "600-185-4100",
    description: "Kit Pastillas de Freno Komatsu WA480",
    brand: "Komatsu",
    category: "frenos",
    compatibleMachines: ["maq-012"],
    stock: 6,
    minStock: 4,
    warehouse: "Bodega Cali",
    location: "G-02-03",
    unitPrice: 890000,
    listPrice: 1050000,
    discountPct: 15,
    weight: 3.2,
    leadTimeDays: 10,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-22",
  },
  {
    id: "part-013",
    sapCode: "CPP-1013-SA",
    partNumber: "21707132",
    description: "Aceite Transmisión Volvo A40G (Cuñete 20L)",
    brand: "Volvo",
    category: "lubricantes",
    compatibleMachines: ["maq-013"],
    stock: 16,
    minStock: 8,
    warehouse: "Bodega Medellín",
    location: "C-02-05",
    unitPrice: 380000,
    listPrice: 445000,
    discountPct: 15,
    weight: 19.0,
    leadTimeDays: 4,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-18",
  },
  {
    id: "part-014",
    sapCode: "CPP-1014-SA",
    partNumber: "RE504836",
    description: "Sensor Temperatura Motor John Deere 872 GP",
    brand: "John Deere",
    category: "electrico",
    compatibleMachines: ["maq-014"],
    stock: 9,
    minStock: 3,
    warehouse: "Bodega Barranquilla",
    location: "H-01-06",
    unitPrice: 285000,
    listPrice: 335000,
    discountPct: 15,
    weight: 0.12,
    leadTimeDays: 7,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-26",
  },
  {
    id: "part-015",
    sapCode: "CPP-1015-SA",
    partNumber: "1G-8878",
    description: "Neumático 26.5R25 L3/E3 - CAT/Komatsu",
    brand: "Caterpillar",
    category: "neumaticos",
    compatibleMachines: ["maq-012", "maq-015"],
    stock: 8,
    minStock: 4,
    warehouse: "Bodega Bogotá",
    location: "I-01-01",
    unitPrice: 8500000,
    listPrice: 9800000,
    discountPct: 13,
    weight: 285.0,
    leadTimeDays: 15,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-10",
  },
  {
    id: "part-016",
    sapCode: "CPP-1016-SA",
    partNumber: "AT337422",
    description: "Regulador de Tensión Alternador John Deere",
    brand: "John Deere",
    category: "electrico",
    compatibleMachines: ["maq-004", "maq-009", "maq-014"],
    stock: 11,
    minStock: 4,
    warehouse: "Bodega Bogotá",
    location: "D-02-02",
    unitPrice: 195000,
    listPrice: 228000,
    discountPct: 14,
    weight: 0.38,
    leadTimeDays: 6,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-30",
  },
  {
    id: "part-017",
    sapCode: "CPP-1017-SA",
    partNumber: "P550248",
    description: "Kit Filtros Completo Donaldson - Universal Heavy Duty",
    brand: "Donaldson",
    category: "filtros",
    compatibleMachines: ["maq-001", "maq-002", "maq-003", "maq-006", "maq-010"],
    stock: 35,
    minStock: 15,
    warehouse: "Bodega Medellín",
    location: "B-01-01",
    unitPrice: 540000,
    listPrice: 630000,
    discountPct: 14,
    weight: 2.8,
    leadTimeDays: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-02",
  },
  {
    id: "part-018",
    sapCode: "CPP-1018-SA",
    partNumber: "6732-81-8170",
    description: "Inyector Combustible Komatsu PC360 SAA6D114",
    brand: "Komatsu",
    category: "motor",
    compatibleMachines: ["maq-002"],
    stock: 4,
    minStock: 6,
    warehouse: "Bodega Medellín",
    location: "B-04-01",
    unitPrice: 2850000,
    listPrice: 3300000,
    discountPct: 14,
    weight: 0.65,
    leadTimeDays: 21,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-05",
  },
  {
    id: "part-019",
    sapCode: "CPP-1019-SA",
    partNumber: "1614905400",
    description: "Separador Agua-Aceite Compresor Atlas Copco",
    brand: "Atlas Copco",
    category: "filtros",
    compatibleMachines: [],
    stock: 7,
    minStock: 3,
    warehouse: "Bodega Bogotá",
    location: "A-04-02",
    unitPrice: 310000,
    listPrice: 360000,
    discountPct: 14,
    weight: 1.1,
    leadTimeDays: 8,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-11-28",
  },
  {
    id: "part-020",
    sapCode: "CPP-1020-SA",
    partNumber: "87300082",
    description: "Termostato Motor Case 580SN / Tier 4",
    brand: "Case",
    category: "motor",
    compatibleMachines: ["maq-008"],
    stock: 14,
    minStock: 5,
    warehouse: "Bodega Medellín",
    location: "B-05-03",
    unitPrice: 145000,
    listPrice: 170000,
    discountPct: 15,
    weight: 0.22,
    leadTimeDays: 5,
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=200",
    isActive: true,
    lastUpdated: "2024-12-01",
  },
];

// ── Maintenance Activities ────────────────────────────────────────────────────

export const MAINTENANCE_ACTIVITIES: MaintenanceActivity[] = [
  {
    id: "act-001",
    code: "MNT-PM-250",
    name: "PM 250 Horas - Cambio de Aceite y Filtros",
    description: "Mantenimiento preventivo a las 250 horas. Incluye cambio de aceite motor, filtro de aceite, filtro de combustible y revisión visual general.",
    category: "Preventivo",
    laborHours: 3,
    laborRate: 85000,
    parts: [
      { partId: "part-001", sapCode: "CPP-1001-SA", description: "Filtro de Aceite Motor", quantity: 1, unitPrice: 185000 },
      { partId: "part-002", sapCode: "CPP-1002-SA", description: "Filtro Combustible", quantity: 1, unitPrice: 145000 },
    ],
    consumables: [
      { partId: "part-007", sapCode: "CPP-1007-SA", description: "Aceite Motor SAE 15W-40 (20L)", quantity: 1, unitPrice: 420000 },
    ],
    totalPartsPrice: 330000,
    totalConsumablesPrice: 420000,
    totalLaborPrice: 255000,
    totalPrice: 1005000,
    intervalHours: 250,
    intervalMonths: 3,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan"],
    estimatedDuration: "3-4 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-002",
    code: "MNT-PM-500",
    name: "PM 500 Horas - Mantenimiento Completo",
    description: "Mantenimiento preventivo a las 500 horas. Incluye todas las tareas del PM 250 más cambio de filtro de aire, limpieza de radiador y ajuste de correas.",
    category: "Preventivo",
    laborHours: 6,
    laborRate: 85000,
    parts: [
      { partId: "part-001", sapCode: "CPP-1001-SA", description: "Filtro de Aceite Motor", quantity: 1, unitPrice: 185000 },
      { partId: "part-002", sapCode: "CPP-1002-SA", description: "Filtro Combustible", quantity: 2, unitPrice: 145000 },
      { partId: "part-005", sapCode: "CPP-1005-SA", description: "Filtro de Aire Primario", quantity: 1, unitPrice: 125000 },
      { partId: "part-004", sapCode: "CPP-1004-SA", description: "Correa Serpentina", quantity: 1, unitPrice: 89000 },
    ],
    consumables: [
      { partId: "part-007", sapCode: "CPP-1007-SA", description: "Aceite Motor SAE 15W-40 (20L)", quantity: 1, unitPrice: 420000 },
    ],
    totalPartsPrice: 689000,
    totalConsumablesPrice: 420000,
    totalLaborPrice: 510000,
    totalPrice: 1619000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan", "Case", "JCB", "Bobcat"],
    estimatedDuration: "6-8 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-003",
    code: "MNT-PM-1000",
    name: "PM 1000 Horas - Mantenimiento Mayor",
    description: "Mantenimiento preventivo a las 1000 horas. Incluye cambio de todos los filtros, revisión del sistema hidráulico, ajuste de válvulas y análisis de aceite.",
    category: "Preventivo",
    laborHours: 12,
    laborRate: 95000,
    parts: [
      { partId: "part-001", sapCode: "CPP-1001-SA", description: "Filtro de Aceite Motor", quantity: 2, unitPrice: 185000 },
      { partId: "part-002", sapCode: "CPP-1002-SA", description: "Filtro Combustible", quantity: 2, unitPrice: 145000 },
      { partId: "part-003", sapCode: "CPP-1003-SA", description: "Filtro Hidráulico", quantity: 2, unitPrice: 320000 },
      { partId: "part-005", sapCode: "CPP-1005-SA", description: "Filtro de Aire Primario", quantity: 1, unitPrice: 125000 },
      { partId: "part-011", sapCode: "CPP-1011-SA", description: "Filtro Aceite Hidráulico", quantity: 1, unitPrice: 215000 },
    ],
    consumables: [
      { partId: "part-007", sapCode: "CPP-1007-SA", description: "Aceite Motor SAE 15W-40 (20L)", quantity: 2, unitPrice: 420000 },
      { partId: "part-013", sapCode: "CPP-1013-SA", description: "Aceite Transmisión (20L)", quantity: 1, unitPrice: 380000 },
    ],
    totalPartsPrice: 1950000,
    totalConsumablesPrice: 1220000,
    totalLaborPrice: 1140000,
    totalPrice: 4310000,
    intervalHours: 1000,
    intervalMonths: 12,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan"],
    estimatedDuration: "12-16 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-004",
    code: "MNT-HID-REP",
    name: "Reparación Sistema Hidráulico - Cambio de Sellos",
    description: "Reparación del sistema hidráulico principal. Incluye cambio de sellos del cilindro de brazo/cuchara, purga del sistema y prueba de presión.",
    category: "Correctivo",
    laborHours: 8,
    laborRate: 110000,
    parts: [
      { partId: "part-006", sapCode: "CPP-1006-SA", description: "Sello Hidráulico - Kit Brazo", quantity: 1, unitPrice: 680000 },
      { partId: "part-003", sapCode: "CPP-1003-SA", description: "Filtro Hidráulico", quantity: 2, unitPrice: 320000 },
    ],
    consumables: [],
    totalPartsPrice: 1320000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 880000,
    totalPrice: 2200000,
    intervalHours: 0,
    intervalMonths: 0,
    applicableBrands: ["Hitachi", "Komatsu", "Volvo", "Caterpillar", "Doosan"],
    estimatedDuration: "8-10 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-005",
    code: "MNT-FRE-KIT",
    name: "Cambio Kit de Frenos Completo",
    description: "Reemplazo del kit de frenos incluyendo pastillas, discos y calibración del sistema de frenado. Aplica para cargadores frontales y camiones articulados.",
    category: "Preventivo",
    laborHours: 10,
    laborRate: 95000,
    parts: [
      { partId: "part-012", sapCode: "CPP-1012-SA", description: "Kit Pastillas de Freno", quantity: 2, unitPrice: 890000 },
    ],
    consumables: [],
    totalPartsPrice: 1780000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 950000,
    totalPrice: 2730000,
    intervalHours: 2000,
    intervalMonths: 18,
    applicableBrands: ["Komatsu", "Volvo", "Caterpillar"],
    estimatedDuration: "10-12 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-006",
    code: "MNT-ELE-INS",
    name: "Inspección Sistema Eléctrico Completo",
    description: "Diagnóstico y revisión del sistema eléctrico: batería, alternador, arneses, sensores y ECM. Incluye limpieza de terminales y ajuste de conexiones.",
    category: "Inspección",
    laborHours: 4,
    laborRate: 95000,
    parts: [
      { partId: "part-014", sapCode: "CPP-1014-SA", description: "Sensor Temperatura Motor", quantity: 1, unitPrice: 285000 },
      { partId: "part-016", sapCode: "CPP-1016-SA", description: "Regulador de Tensión", quantity: 1, unitPrice: 195000 },
    ],
    consumables: [],
    totalPartsPrice: 480000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 380000,
    totalPrice: 860000,
    intervalHours: 1000,
    intervalMonths: 12,
    applicableBrands: ["John Deere", "Caterpillar", "Komatsu", "Volvo"],
    estimatedDuration: "4-5 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-007",
    code: "MNT-NEU-ROT",
    name: "Rotación y Balanceo de Neumáticos",
    description: "Rotación cruzada de neumáticos, verificación de presión, inspección de desgaste y reapriete de tuercas al torque especificado por el fabricante.",
    category: "Preventivo",
    laborHours: 4,
    laborRate: 75000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 300000,
    totalPrice: 300000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["Komatsu", "Volvo", "Caterpillar", "John Deere"],
    estimatedDuration: "4 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-008",
    code: "MNT-CAD-INS",
    name: "Inspección y Ajuste de Cadenas de Rodamiento",
    description: "Verificación del estado de cadenas, rodillos y zapatas. Ajuste de tensión según parámetros del fabricante y lubricación del sistema.",
    category: "Inspección",
    laborHours: 5,
    laborRate: 85000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 425000,
    totalPrice: 425000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["Caterpillar", "Komatsu", "Hitachi", "Doosan"],
    estimatedDuration: "5-6 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-009",
    code: "MNT-MOT-INY",
    name: "Cambio de Inyectores de Combustible",
    description: "Sustitución de inyectores de combustible con diagnóstico previo por scanner. Incluye prueba de funcionamiento y ajuste de curva de inyección.",
    category: "Correctivo",
    laborHours: 14,
    laborRate: 110000,
    parts: [
      { partId: "part-018", sapCode: "CPP-1018-SA", description: "Inyector Combustible Komatsu", quantity: 6, unitPrice: 2850000 },
    ],
    consumables: [],
    totalPartsPrice: 17100000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 1540000,
    totalPrice: 18640000,
    intervalHours: 8000,
    intervalMonths: 48,
    applicableBrands: ["Komatsu"],
    estimatedDuration: "14-16 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-010",
    code: "MNT-RAD-LIM",
    name: "Limpieza y Revisión Sistema de Enfriamiento",
    description: "Limpieza a presión del radiador, revisión de mangueras, termostato, bomba de agua y líquido refrigerante. Prueba de presión del sistema.",
    category: "Preventivo",
    laborHours: 4,
    laborRate: 75000,
    parts: [
      { partId: "part-020", sapCode: "CPP-1020-SA", description: "Termostato Motor", quantity: 1, unitPrice: 145000 },
    ],
    consumables: [],
    totalPartsPrice: 145000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 300000,
    totalPrice: 445000,
    intervalHours: 1000,
    intervalMonths: 12,
    applicableBrands: ["Case", "JCB", "Bobcat", "Caterpillar"],
    estimatedDuration: "4 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-011",
    code: "MNT-BOM-HID",
    name: "Sustitución Bomba Hidráulica Principal",
    description: "Reemplazo de la bomba hidráulica de pistones variables. Incluye limpieza del depósito, cambio de aceite hidráulico completo y purga del sistema.",
    category: "Correctivo",
    laborHours: 20,
    laborRate: 120000,
    parts: [
      { partId: "part-010", sapCode: "CPP-1010-SA", description: "Bomba Hidráulica Doosan Tandem", quantity: 1, unitPrice: 7200000 },
      { partId: "part-003", sapCode: "CPP-1003-SA", description: "Filtro Hidráulico", quantity: 3, unitPrice: 320000 },
    ],
    consumables: [],
    totalPartsPrice: 8160000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 2400000,
    totalPrice: 10560000,
    intervalHours: 0,
    intervalMonths: 0,
    applicableBrands: ["Doosan"],
    estimatedDuration: "20-24 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-012",
    code: "MNT-GEN-DIA",
    name: "Diagnóstico General con Scanner OEM",
    description: "Diagnóstico electrónico completo con scanner original del fabricante. Lectura de códigos de falla, análisis de parámetros del motor y tren de potencia.",
    category: "Inspección",
    laborHours: 2,
    laborRate: 120000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 240000,
    totalPrice: 240000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan", "Case", "JCB", "Liebherr"],
    estimatedDuration: "2 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-013",
    code: "MNT-ACE-ANL",
    name: "Análisis de Aceite por Laboratorio",
    description: "Toma de muestras y análisis espectrométrico de aceite motor y sistema hidráulico para detección temprana de desgastes y contaminación.",
    category: "Inspección",
    laborHours: 1,
    laborRate: 75000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 75000,
    totalPrice: 365000,
    intervalHours: 250,
    intervalMonths: 3,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan", "Liebherr"],
    estimatedDuration: "1 hora + 5 días laboratorio",
    techniciansRequired: 1,
  },
  {
    id: "act-014",
    code: "MNT-COR-REP",
    name: "Cambio de Correas de Distribución y Accesorios",
    description: "Reemplazo de correa de distribución, tensores y polea loca. Incluye verificación de sincronización del motor y prueba de funcionamiento.",
    category: "Preventivo",
    laborHours: 8,
    laborRate: 95000,
    parts: [
      { partId: "part-004", sapCode: "CPP-1004-SA", description: "Correa Serpentina JD", quantity: 2, unitPrice: 89000 },
    ],
    consumables: [],
    totalPartsPrice: 178000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 760000,
    totalPrice: 938000,
    intervalHours: 2000,
    intervalMonths: 24,
    applicableBrands: ["John Deere"],
    estimatedDuration: "8 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-015",
    code: "MNT-TUR-REV",
    name: "Revisión y Limpieza Turbocompresor",
    description: "Desmontaje, limpieza y evaluación del turbocompresor. Verificación de holguras radiales y axiales, cambio de sellos si es necesario.",
    category: "Preventivo",
    laborHours: 6,
    laborRate: 110000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 660000,
    totalPrice: 660000,
    intervalHours: 2000,
    intervalMonths: 18,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "Liebherr", "Doosan"],
    estimatedDuration: "6-7 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-016",
    code: "MNT-EJE-INS",
    name: "Inspección Ejes y Diferencial",
    description: "Revisión del estado de ejes cardán, diferencial y caja de transferencia. Cambio de aceite de ejes y verificación de juego en ruedas.",
    category: "Preventivo",
    laborHours: 7,
    laborRate: 85000,
    parts: [],
    consumables: [
      { partId: "part-013", sapCode: "CPP-1013-SA", description: "Aceite Transmisión (20L)", quantity: 1, unitPrice: 380000 },
    ],
    totalPartsPrice: 0,
    totalConsumablesPrice: 380000,
    totalLaborPrice: 595000,
    totalPrice: 975000,
    intervalHours: 1000,
    intervalMonths: 12,
    applicableBrands: ["Volvo", "Komatsu", "Caterpillar", "John Deere"],
    estimatedDuration: "7-8 horas",
    techniciansRequired: 2,
  },
  {
    id: "act-017",
    code: "MNT-SEP-AGU",
    name: "Cambio Separador Agua-Aceite Compresor",
    description: "Sustitución del separador agua-aceite del compresor de aire, limpieza de válvulas de mínima presión y revisión general del compresor.",
    category: "Preventivo",
    laborHours: 3,
    laborRate: 85000,
    parts: [
      { partId: "part-019", sapCode: "CPP-1019-SA", description: "Separador Agua-Aceite Compresor", quantity: 1, unitPrice: 310000 },
    ],
    consumables: [],
    totalPartsPrice: 310000,
    totalConsumablesPrice: 0,
    totalLaborPrice: 255000,
    totalPrice: 565000,
    intervalHours: 1000,
    intervalMonths: 12,
    applicableBrands: ["Atlas Copco"],
    estimatedDuration: "3 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-018",
    code: "MNT-KIT-GEN",
    name: "Kit Mantenimiento General - Todos Filtros",
    description: "Cambio completo de todos los filtros del equipo usando kit Donaldson certificado. Incluye filtros de aire, aceite, combustible e hidráulico.",
    category: "Preventivo",
    laborHours: 5,
    laborRate: 85000,
    parts: [
      { partId: "part-017", sapCode: "CPP-1017-SA", description: "Kit Filtros Donaldson Universal", quantity: 1, unitPrice: 540000 },
    ],
    consumables: [
      { partId: "part-007", sapCode: "CPP-1007-SA", description: "Aceite Motor SAE 15W-40 (20L)", quantity: 1, unitPrice: 420000 },
    ],
    totalPartsPrice: 540000,
    totalConsumablesPrice: 420000,
    totalLaborPrice: 425000,
    totalPrice: 1385000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan", "Case"],
    estimatedDuration: "5-6 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-019",
    code: "MNT-JCB-PM500",
    name: "PM 500 Horas JCB - Servicio Especializado",
    description: "Mantenimiento preventivo JCB a 500 horas. Cambio de aceite, filtros, revisión del sistema EcoMAX y actualización de software ECM si aplica.",
    category: "Preventivo",
    laborHours: 6,
    laborRate: 95000,
    parts: [
      { partId: "part-009", sapCode: "CPP-1009-SA", description: "Bomba Hidráulica JCB", quantity: 1, unitPrice: 4850000 },
    ],
    consumables: [
      { partId: "part-007", sapCode: "CPP-1007-SA", description: "Aceite Motor SAE 15W-40 (20L)", quantity: 1, unitPrice: 420000 },
    ],
    totalPartsPrice: 4850000,
    totalConsumablesPrice: 420000,
    totalLaborPrice: 570000,
    totalPrice: 5840000,
    intervalHours: 500,
    intervalMonths: 6,
    applicableBrands: ["JCB"],
    estimatedDuration: "6-8 horas",
    techniciansRequired: 1,
  },
  {
    id: "act-020",
    code: "MNT-CAB-INS",
    name: "Inspección Cabina y Sistemas de Seguridad ROPS",
    description: "Verificación del estado de cabina ROPS/FOPS, cinturones de seguridad, espejos, alarmas de retroceso, luces y bocina. Según normativa colombiana.",
    category: "Inspección",
    laborHours: 2,
    laborRate: 75000,
    parts: [],
    consumables: [],
    totalPartsPrice: 0,
    totalConsumablesPrice: 0,
    totalLaborPrice: 150000,
    totalPrice: 150000,
    intervalHours: 250,
    intervalMonths: 3,
    applicableBrands: ["Caterpillar", "Komatsu", "Volvo", "John Deere", "Hitachi", "Doosan", "Case", "JCB", "Bobcat", "Liebherr"],
    estimatedDuration: "2 horas",
    techniciansRequired: 1,
  },
];

// ── Maintenance Schedules ─────────────────────────────────────────────────────

export const MAINTENANCE_SCHEDULES: MaintenanceSchedule[] = [
  {
    id: "sched-001",
    machineId: "maq-001",
    machineName: "Caterpillar D6T - CAT-D6T-2021-COL001",
    customerId: "cust-001",
    customerName: "Constructora Bolívar S.A.",
    activityId: "act-002",
    activityName: "PM 500 Horas - Mantenimiento Completo",
    status: "scheduled",
    scheduledDate: "2025-01-15",
    technicianId: "user-005",
    technicianName: "Héctor Ramírez",
    estimatedHours: 6,
    totalCost: 1619000,
    notes: "Programado en sitio de obra. Coordinar con obra para parada de equipo.",
    workOrderNumber: "OT-2025-00145",
  },
  {
    id: "sched-002",
    machineId: "maq-002",
    machineName: "Komatsu PC360-10 - KOM-PC360-2020-COL002",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    activityId: "act-003",
    activityName: "PM 1000 Horas - Mantenimiento Mayor",
    status: "in_progress",
    scheduledDate: "2024-12-05",
    technicianId: "user-005",
    technicianName: "Héctor Ramírez",
    estimatedHours: 12,
    actualHours: 8,
    totalCost: 4310000,
    notes: "En ejecución. Se detectó desgaste en rodamiento tensor de cadena. Solicitar repuesto.",
    workOrderNumber: "OT-2024-00892",
  },
  {
    id: "sched-003",
    machineId: "maq-006",
    machineName: "Hitachi ZX350LC-6 - HIT-ZX350-2020-COL006",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    activityId: "act-004",
    activityName: "Reparación Sistema Hidráulico - Cambio de Sellos",
    status: "overdue",
    scheduledDate: "2024-11-20",
    technicianId: "user-005",
    technicianName: "Héctor Ramírez",
    estimatedHours: 8,
    totalCost: 2200000,
    notes: "⚠️ VENCIDA. Fuga hidráulica activa. Equipo paralizado. Prioridad máxima.",
    workOrderNumber: "OT-2024-00834",
  },
  {
    id: "sched-004",
    machineId: "maq-010",
    machineName: "Doosan DX380LC-7 - DOS-DX380-2020-COL010",
    customerId: "cust-002",
    customerName: "Mineros S.A.",
    activityId: "act-011",
    activityName: "Sustitución Bomba Hidráulica Principal",
    status: "in_progress",
    scheduledDate: "2024-12-03",
    technicianId: "user-005",
    technicianName: "Héctor Ramírez",
    estimatedHours: 20,
    actualHours: 12,
    totalCost: 10560000,
    notes: "Reemplazo de bomba tandem. Pieza en tránsito desde almacén Medellín.",
    workOrderNumber: "OT-2024-00879",
  },
  {
    id: "sched-005",
    machineId: "maq-003",
    machineName: "Volvo EC480E - VOL-EC480-2022-COL003",
    customerId: "cust-003",
    customerName: "Cementos Argos S.A.",
    activityId: "act-001",
    activityName: "PM 250 Horas - Cambio de Aceite y Filtros",
    status: "completed",
    scheduledDate: "2024-11-20",
    completedDate: "2024-11-20",
    technicianId: "user-005",
    technicianName: "Héctor Ramírez",
    estimatedHours: 3,
    actualHours: 3.5,
    totalCost: 1005000,
    notes: "Completado sin novedades. Próximo PM a las 2500 horas.",
    workOrderNumber: "OT-2024-00821",
  },
];

// ── Users ─────────────────────────────────────────────────────────────────────

export const USERS: User[] = [
  {
    id: "user-001",
    name: "Santiago Gómez",
    email: "sgomez@partequipos.com",
    role: "Administrator",
    avatar: "SG",
    department: "Tecnología",
    phone: "+57 310 555 0101",
    isActive: true,
    lastLogin: "2024-12-05T08:32:00Z",
    createdAt: "2021-01-10",
    permissions: ["*"],
  },
  {
    id: "user-002",
    name: "Valentina Herrera",
    email: "vherrera@partequipos.com",
    role: "Coordinator",
    avatar: "VH",
    department: "Operaciones",
    phone: "+57 311 555 0202",
    isActive: true,
    lastLogin: "2024-12-05T07:15:00Z",
    createdAt: "2021-05-20",
    permissions: ["machines:read", "machines:write", "maintenance:read", "maintenance:write", "parts:read", "customers:read"],
  },
  {
    id: "user-003",
    name: "Camilo Ospina",
    email: "cospina@partequipos.com",
    role: "Viewer",
    avatar: "CO",
    department: "Finanzas",
    phone: "+57 312 555 0303",
    isActive: true,
    lastLogin: "2024-12-04T14:22:00Z",
    createdAt: "2022-03-08",
    permissions: ["dashboard:read", "reports:read"],
  },
  {
    id: "user-004",
    name: "Daniela Ruiz",
    email: "druiz@partequipos.com",
    role: "Sales Advisor",
    avatar: "DR",
    department: "Ventas",
    phone: "+57 313 555 0404",
    isActive: true,
    lastLogin: "2024-12-05T09:47:00Z",
    createdAt: "2021-08-15",
    permissions: ["customers:read", "customers:write", "parts:read", "quotes:read", "quotes:write", "machines:read"],
  },
  {
    id: "user-005",
    name: "Héctor Ramírez",
    email: "hramirez@partequipos.com",
    role: "Technician",
    avatar: "HR",
    department: "Servicio Técnico",
    phone: "+57 314 555 0505",
    isActive: true,
    lastLogin: "2024-12-05T06:00:00Z",
    createdAt: "2020-11-01",
    permissions: ["machines:read", "maintenance:read", "maintenance:write", "parts:read"],
  },
];

// ── Dashboard KPIs ────────────────────────────────────────────────────────────

export const DASHBOARD_KPIS: DashboardKPI = {
  totalMachines: 15,
  operationalMachines: 9,
  machinesInMaintenance: 2,
  idleMachines: 2,
  criticalMachines: 2,
  scheduledMaintenances: 3,
  completedMaintenancesThisMonth: 8,
  overdueMaintenances: 1,
  totalPartsInStock: 210,
  lowStockParts: 5,
  monthlyRevenue: 48500000,
  revenueGrowth: 12.4,
  totalCustomers: 8,
  activeCustomers: 6,
  avgMaintenanceCost: 3250000,
  partsOrderedThisMonth: 47,
  monthlyRevenueHistory: [
    { month: "Jun 2024", revenue: 32000000, target: 38000000 },
    { month: "Jul 2024", revenue: 35500000, target: 38000000 },
    { month: "Ago 2024", revenue: 38200000, target: 40000000 },
    { month: "Sep 2024", revenue: 41800000, target: 42000000 },
    { month: "Oct 2024", revenue: 43100000, target: 44000000 },
    { month: "Nov 2024", revenue: 46200000, target: 46000000 },
    { month: "Dic 2024", revenue: 48500000, target: 48000000 },
  ],
  maintenanceByBrand: [
    { brand: "Caterpillar", count: 5, color: "#FFCD11" },
    { brand: "Komatsu", count: 4, color: "#003087" },
    { brand: "Volvo", count: 3, color: "#003E7E" },
    { brand: "John Deere", count: 3, color: "#367C2B" },
    { brand: "Hitachi", count: 2, color: "#E4003B" },
    { brand: "Doosan", count: 2, color: "#00519E" },
    { brand: "Liebherr", count: 1, color: "#F7A800" },
    { brand: "Case", count: 1, color: "#D02E22" },
    { brand: "JCB", count: 1, color: "#FDD300" },
    { brand: "Bobcat", count: 1, color: "#F47920" },
  ],
  machineStatusDistribution: [
    { status: "Operacional", count: 9, color: "#22c55e" },
    { status: "Mantenimiento", count: 2, color: "#3b82f6" },
    { status: "Inactivo", count: 2, color: "#94a3b8" },
    { status: "Crítico", count: 2, color: "#ef4444" },
  ],
  topPartsConsumed: [
    { name: "Filtro de Aceite Motor CAT", quantity: 18, revenue: 3330000 },
    { name: "Kit Filtros Donaldson", quantity: 14, revenue: 7560000 },
    { name: "Filtro Combustible Komatsu", quantity: 12, revenue: 1740000 },
    { name: "Aceite Motor SAE 15W-40", quantity: 11, revenue: 4620000 },
    { name: "Filtro Hidráulico Volvo", quantity: 9, revenue: 2880000 },
  ],
};

// ── Activity Log ──────────────────────────────────────────────────────────────

export const ACTIVITY_LOG: ActivityLog[] = [
  {
    id: "log-001",
    timestamp: "2024-12-05T09:47:22Z",
    userId: "user-004",
    userName: "Daniela Ruiz",
    userRole: "Sales Advisor",
    action: "Cotización enviada",
    module: "Repuestos",
    description: "Cotización CPP-Q-2024-0892 enviada a Mineros S.A. por $18.640.000",
    entityId: "CPP-Q-2024-0892",
    entityType: "Cotización",
  },
  {
    id: "log-002",
    timestamp: "2024-12-05T09:12:05Z",
    userId: "user-005",
    userName: "Héctor Ramírez",
    userRole: "Technician",
    action: "OT actualizada",
    module: "Mantenimiento",
    description: "OT-2024-00892 (Komatsu PC360): actualización de avance al 65%",
    entityId: "sched-002",
    entityType: "Orden de Trabajo",
  },
  {
    id: "log-003",
    timestamp: "2024-12-05T08:55:30Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    userRole: "Administrator",
    action: "Usuario creado",
    module: "Administración",
    description: "Nuevo técnico agregado al sistema: Juan Carlos Pérez",
    entityId: "user-006",
    entityType: "Usuario",
  },
  {
    id: "log-004",
    timestamp: "2024-12-05T08:32:10Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    userRole: "Administrator",
    action: "Inicio de sesión",
    module: "Seguridad",
    description: "Acceso exitoso desde 190.26.45.12",
  },
  {
    id: "log-005",
    timestamp: "2024-12-04T17:30:00Z",
    userId: "user-002",
    userName: "Valentina Herrera",
    userRole: "Coordinator",
    action: "Equipo actualizado",
    module: "Equipos",
    description: "Hitachi ZX350 marcado como CRÍTICO. Alerta enviada al asesor y coordinador.",
    entityId: "maq-006",
    entityType: "Equipo",
  },
  {
    id: "log-006",
    timestamp: "2024-12-04T16:10:44Z",
    userId: "user-005",
    userName: "Héctor Ramírez",
    userRole: "Technician",
    action: "OT iniciada",
    module: "Mantenimiento",
    description: "Inicio de OT-2024-00879: Cambio bomba hidráulica Doosan DX380",
    entityId: "sched-004",
    entityType: "Orden de Trabajo",
  },
  {
    id: "log-007",
    timestamp: "2024-12-04T14:00:00Z",
    userId: "user-002",
    userName: "Valentina Herrera",
    userRole: "Coordinator",
    action: "OT programada",
    module: "Mantenimiento",
    description: "OT-2025-00145 programada para 2025-01-15: PM 500H Caterpillar D6T",
    entityId: "sched-001",
    entityType: "Orden de Trabajo",
  },
  {
    id: "log-008",
    timestamp: "2024-12-04T11:25:18Z",
    userId: "user-004",
    userName: "Daniela Ruiz",
    userRole: "Sales Advisor",
    action: "Repuesto consultado",
    module: "Repuestos",
    description: "Consulta de disponibilidad: Sello Hidráulico Hitachi (CPP-1006-SA). Stock: 3 unid.",
    entityId: "part-006",
    entityType: "Repuesto",
  },
  {
    id: "log-009",
    timestamp: "2024-12-03T15:45:00Z",
    userId: "user-005",
    userName: "Héctor Ramírez",
    userRole: "Technician",
    action: "OT completada",
    module: "Mantenimiento",
    description: "OT-2024-00821 completada: PM 250H Volvo EC480E. Duración real: 3.5h",
    entityId: "sched-005",
    entityType: "Orden de Trabajo",
  },
  {
    id: "log-010",
    timestamp: "2024-12-03T10:00:00Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    userRole: "Administrator",
    action: "Reporte exportado",
    module: "Reportes",
    description: "Exportación de reporte de KPIs noviembre 2024 en formato PDF",
  },
];

// ── Audit Log ─────────────────────────────────────────────────────────────────

export const AUDIT_LOG: AuditLog[] = [
  {
    id: "audit-001",
    timestamp: "2024-12-05T09:47:22Z",
    userId: "user-004",
    userName: "Daniela Ruiz",
    action: "CREATE",
    module: "Cotizaciones",
    entityId: "CPP-Q-2024-0892",
    entityType: "Cotización",
    ipAddress: "192.168.1.45",
    userAgent: "Chrome/120.0.0.0",
  },
  {
    id: "audit-002",
    timestamp: "2024-12-05T08:55:30Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    action: "CREATE",
    module: "Usuarios",
    entityId: "user-006",
    entityType: "Usuario",
    changes: [
      { field: "nombre", oldValue: "", newValue: "Juan Carlos Pérez" },
      { field: "rol", oldValue: "", newValue: "Technician" },
      { field: "estado", oldValue: "", newValue: "Activo" },
    ],
    ipAddress: "190.26.45.12",
    userAgent: "Chrome/120.0.0.0",
  },
  {
    id: "audit-003",
    timestamp: "2024-12-04T17:30:00Z",
    userId: "user-002",
    userName: "Valentina Herrera",
    action: "UPDATE",
    module: "Equipos",
    entityId: "maq-006",
    entityType: "Equipo",
    changes: [
      { field: "status", oldValue: "operational", newValue: "critical" },
      { field: "notes", oldValue: "Operando normalmente", newValue: "⚠️ ALERTA: Fuga hidráulica detectada. Requiere intervención urgente." },
    ],
    ipAddress: "192.168.1.52",
    userAgent: "Firefox/121.0",
  },
  {
    id: "audit-004",
    timestamp: "2024-12-04T11:25:18Z",
    userId: "user-004",
    userName: "Daniela Ruiz",
    action: "VIEW",
    module: "Repuestos",
    entityId: "part-006",
    entityType: "Repuesto",
    ipAddress: "192.168.1.45",
    userAgent: "Chrome/120.0.0.0",
  },
  {
    id: "audit-005",
    timestamp: "2024-12-03T10:00:00Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    action: "EXPORT",
    module: "Reportes",
    entityId: "RPT-2024-11",
    entityType: "Reporte",
    ipAddress: "190.26.45.12",
    userAgent: "Chrome/120.0.0.0",
  },
  {
    id: "audit-006",
    timestamp: "2024-12-05T08:32:10Z",
    userId: "user-001",
    userName: "Santiago Gómez",
    action: "LOGIN",
    module: "Seguridad",
    entityId: "user-001",
    entityType: "Sesión",
    ipAddress: "190.26.45.12",
    userAgent: "Chrome/120.0.0.0",
  },
];

// ── Derived / Helper exports ──────────────────────────────────────────────────

/** All unique brands across the machines dataset */
export const BRANDS = Array.from(new Set(MACHINES.map((m) => m.brand))).sort();

/** All unique machine categories */
export const MACHINE_CATEGORIES = Array.from(new Set(MACHINES.map((m) => m.category))).sort();

/** All warehouses */
export const WAREHOUSES = Array.from(new Set(SPARE_PARTS.map((p) => p.warehouse))).sort();

/** Default mock user (Administrator) */
export const DEFAULT_USER: User = USERS[0];

/** Status colour mapping */
export const STATUS_COLORS: Record<MachineStatus, string> = {
  operational: "#22c55e",
  maintenance: "#3b82f6",
  idle: "#94a3b8",
  critical: "#ef4444",
};

/** Maintenance status colour mapping */
export const MAINTENANCE_STATUS_COLORS: Record<MaintenanceStatus, string> = {
  scheduled: "#3b82f6",
  in_progress: "#f59e0b",
  completed: "#22c55e",
  overdue: "#ef4444",
};

/** Status labels in Spanish */
export const STATUS_LABELS: Record<MachineStatus, string> = {
  operational: "Operacional",
  maintenance: "En Mantenimiento",
  idle: "Inactivo",
  critical: "Crítico",
};

/** Maintenance status labels in Spanish */
export const MAINTENANCE_STATUS_LABELS: Record<MaintenanceStatus, string> = {
  scheduled: "Programado",
  in_progress: "En Progreso",
  completed: "Completado",
  overdue: "Vencido",
};

/** Format COP currency */
export function formatCOP(value: number): string {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}
