import type { TemparioMantenimiento } from '@/types/database';

/** Temparios mock alineados al esquema Supabase — fallback sin conexión */
export const MOCK_TEMPARIOS: TemparioMantenimiento[] = [
  {
    id: 'mock-1',
    marca: 'Case',
    linea: 'Minicargador',
    modelo: 'SR175B',
    tipo_item: 'Repuesto',
    item: 'Filtro aceite motor',
    unidad_medida: 'Unidad',
    cantidad: 1,
    frecuencia_horas: 250,
    referencia_genuina: '84475542',
    referencia_fleetguard: 'LF16011',
    referencia_donaldson: 'P551132',
    tiempo_horas: 0,
    procedimiento: 'N/A',
    avisos_claves: 'N/A',
    precio_unitario: 85000,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-2',
    marca: 'Case',
    linea: 'Minicargador',
    modelo: 'SR175B',
    tipo_item: 'Consumible',
    item: 'Aceite de Motor 15W-40',
    unidad_medida: 'L',
    cantidad: 8,
    frecuencia_horas: 250,
    aceite_homologado: '15W-40 CI-4',
    tiempo_horas: 0,
    precio_unitario: 18500,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-3',
    marca: 'Case',
    linea: 'Minicargador',
    modelo: 'SR175B',
    tipo_item: 'Actividad',
    item: 'Cambio de aceite y filtros',
    unidad_medida: 'Servicio',
    cantidad: 1,
    frecuencia_horas: 250,
    tiempo_horas: 2.5,
    procedimiento: 'Drenar aceite, reemplazar filtros, rellenar según cartilla OEM',
    avisos_claves: 'Verificar torque de tapón de carter',
    precio_unitario: 0,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-4',
    marca: 'Case',
    linea: 'Minicargador',
    modelo: 'SR175B',
    tipo_item: 'Actividad',
    item: 'Inspección sistema hidráulico',
    unidad_medida: 'Servicio',
    cantidad: 1,
    frecuencia_horas: 1000,
    tiempo_horas: 3,
    procedimiento: 'Revisión de mangueras, filtros y niveles',
    precio_unitario: 0,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-5',
    marca: 'Case',
    linea: 'Minicargador',
    modelo: 'SR175B',
    tipo_item: 'Repuesto',
    item: 'Filtro hidráulico retorno',
    unidad_medida: 'Unidad',
    cantidad: 1,
    frecuencia_horas: 1000,
    ref_sap_original: '87365432',
    tiempo_horas: 0,
    precio_unitario: 320000,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-6',
    marca: 'Hitachi',
    linea: 'Excavadora',
    modelo: 'ZX330-6',
    tipo_item: 'Repuesto',
    item: 'Filtro aceite motor N°1',
    unidad_medida: 'Unidad',
    cantidad: 1,
    frecuencia_horas: 250,
    ref_sap_original: '898375860-0',
    referencia_fleetguard: 'LF16045',
    tiempo_horas: 0,
    precio_unitario: 145000,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
  {
    id: 'mock-7',
    marca: 'Hitachi',
    linea: 'Excavadora',
    modelo: 'ZX330-6',
    tipo_item: 'Actividad',
    item: 'Servicio 250 horas',
    unidad_medida: 'Servicio',
    cantidad: 1,
    frecuencia_horas: 250,
    tiempo_horas: 4,
    procedimiento: 'Mantenimiento preventivo 250H según manual Hitachi',
    precio_unitario: 0,
    tarifa_mano_obra_h: 110000,
    activo: true,
  },
];

export const MOCK_BRAND_MODELS: Record<string, string[]> = {
  Case: ['SR175B', 'SV340B', '580N'],
  Hitachi: ['ZX330-6', 'ZX350LC-6', 'ZX210-6'],
  Caterpillar: ['320', '336', '950'],
  Komatsu: ['PC200', 'PC360', 'WA470'],
  Volvo: ['EC220', 'EC480', 'L110H'],
  'John Deere': ['310SL', '644K', '850K'],
  Bobcat: ['E35', 'S650', 'T650'],
  Liebherr: ['R920', 'R936'],
  JCB: ['3CX', 'JS220'],
  Doosan: ['DX225', 'DX300'],
};

export function getMockMarcas(): string[] {
  return Object.keys(MOCK_BRAND_MODELS).sort();
}

export function getMockModelos(marca: string): string[] {
  return MOCK_BRAND_MODELS[marca] ?? [];
}
